services:
#    kernix_forum.example:
#        class: Kernix\ForumBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    kernix_forum.antispam:
        class: Kernix\ForumBundle\Antispam\KernixAntispam
        arguments: [@mailer, %locale%, 50]